### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by reikopm** [marinebon/infographiq#23]
update: Apologies, I'm a bit confused. Originally I cloned cr-metrics. Now I see that there are some new repositories. I think I need info-mb. 

 <ignore this>
I have the data as csv files, and I've written R code to generate the graphs I want. I've cloned the repository to create the web page for the infographiq. Can I just upload my phytoplankton html file? 
or
In the indicators.csv file there is a column called image_url. Can I put the url to my graphs there?

I'm looking for an easy way to do this without making changes to the master.
</ignore this>

**Comment by 7yl4r** [comment]
Sorry there is conflicting information here because of the rapid development changes. I can schedule anytime today through Friday (8-5 eastern) if you would like to plan a call & screenshare.

`cr-metrics` is an older and now outdated repository. Ben re-packaged the functionality there into "infographiq". `info-mb` is indeed the one you want.

> I have the data as csv files, and I've written R code to generate the graphs I want. I've cloned the repository to create the web page for the infographiq. Can I just upload my phytoplankton html file? or In the indicators.csv file there is a column called image_url. Can I put the url to my graphs there? 

`infographiq` works from the csv data files directly to make graphics in a common style. The [`plot_indicators.csv` in `info-mb`](https://github.com/marinebon/info-mb/blob/master/plot_indicators.csv) is not correct; it should instead resemble [info-demo/plot_indicators.csv](https://github.com/marinebon/info-mb/blob/master/plot_indicators.csv) as outlined by [this overview](https://github.com/marinebon/infographiq/tree/master/Docs).

Putting a url to your graphs in image or html form is not supported, but I could add this functionality.

> I'm looking for an easy way to do this without making changes to the master.

don't be shy about modifying the master, every commit can be reverted and I don't think anyone else is working on `info-mb` right now.

**Comment by reikopm** [comment]
Thank you Tyler for your answer and offer of a consultation. I am slowly working through the documentation and your info-fk site.  I think I understand the new flow [she says optimistically ;o) ] and I can use your FK site to help guide me.  I'll use the info-demo site for the plot_indicators.csv file.
